from dataclasses import dataclass
from enum import Enum


class DecisionFailureCode(Enum):
    ACTION_NOT_AVAILABLE = "ACTION_NOT_AVAILABLE"
    ACTION_NOT_MUTATING = "ACTION_NOT_MUTATING"
    ATTEMPT_AUTHORITY_REQUIRED = "ATTEMPT_AUTHORITY_REQUIRED"
    ATTEMPT_LEASE_REQUIRED = "ATTEMPT_LEASE_REQUIRED"
    ATTEMPT_LEASE_EXPIRED = "ATTEMPT_LEASE_EXPIRED"
    ATTEMPT_NOT_FOUND = "ATTEMPT_NOT_FOUND"
    DEPENDENCY_NOT_SATISFIED = "DEPENDENCY_NOT_SATISFIED"
    HISTORY_RECORD_EXISTS = "HISTORY_RECORD_EXISTS"
    ITEM_ALREADY_EXISTS = "ITEM_ALREADY_EXISTS"
    ITEM_DEFINITION_INVALID = "ITEM_DEFINITION_INVALID"
    ITEM_DEFINITION_STALE = "ITEM_DEFINITION_STALE"
    ITEM_DEFINITION_LIFECYCLE_INVALID = "ITEM_DEFINITION_LIFECYCLE_INVALID"
    ITEM_DEPENDENCY_CYCLE = "ITEM_DEPENDENCY_CYCLE"
    ITEM_NOT_FOUND = "ITEM_NOT_FOUND"
    LIVE_DEPENDENTS = "LIVE_DEPENDENTS"
    LEASE_FENCED = "LEASE_FENCED"
    PROPOSAL_NOT_FOUND = "PROPOSAL_NOT_FOUND"
    PROPOSAL_ALREADY_EXISTS = "PROPOSAL_ALREADY_EXISTS"
    PROPOSAL_INVALID = "PROPOSAL_INVALID"
    TRANSITION_INPUT_INVALID = "TRANSITION_INPUT_INVALID"


@dataclass(frozen=True, slots=True)
class DecisionFailure:
    code: DecisionFailureCode
    message: str


type DecisionResult[T] = T | DecisionFailure
