"""Stable MCP wire tool names shared by registration and launch recipes."""

ITEM_STATUS_TOOL = "pinboard_item_status"
PROPOSAL_CREATE_TOOL = "pinboard_proposal_create"
BRIEF_PUBLISH_TOOL = "pinboard_brief_publish"
OVERVIEW_TOOL = "pinboard_overview"
ACTIONS_TOOL = "pinboard_actions"
ATTEMPT_INSPECT_TOOL = "pinboard_attempt_inspect"
CORRECTION_CONTEXT_TOOL = "pinboard_correction_context"
CANDIDATE_RESTORE_TOOL = "pinboard_candidate_restore"
CANDIDATE_OBSERVE_TOOL = "pinboard_candidate_observe"
ARTIFACT_VERIFY_TOOL = "pinboard_artifact_verify"
PREPARATION_AUTHORITY_TOOL = "pinboard_preparation_authority"
ATTEMPT_AUTHORITY_TOOL = "pinboard_attempt_authority"
TRANSITION_TOOL = "pinboard_transition"
DISPATCH_TOOL = "pinboard_dispatch"
REVIEW_JOB_TOOL = "pinboard_review_job"
ITEM_DEFINITION_TOOL = "pinboard_item_definition"
BRIEF_REVIEW_TOOL = "pinboard_brief_review"
BRIEF_CONTRACT_TOOL = "pinboard_brief_contract"
BRIEF_SOURCES_TOOL = "pinboard_brief_sources"
ORDER_TOOL = "pinboard_order"
PARALLEL_PREVIEW_TOOL = "pinboard_parallel_preview"
