# Code generated by python -m codegen.replacements.compiler; DO NOT EDIT.

from dataclasses import dataclass

import msgspec

from pinboard.application import stored_state
from pinboard.domain import work_models


class HandoverPlannedReplacement(msgspec.Struct, frozen=True, forbid_unknown_fields=True):
    affected_item_id: str
    relation_revision: int
    replacement_item_id: str
    replacement_cost: str
    status: work_models.PlannedReplacementStatus
    recorded_by: str
    recorded_at: str
    accepted_project_revision: int


class HandoverReplacementDisposition(msgspec.Struct, frozen=True, forbid_unknown_fields=True):
    affected_item_id: str
    relation_revision: int
    rationale: str
    accepted_cost: str
    recorded_by: str
    recorded_at: str
    accepted_project_revision: int


type ProjectedPlannedReplacements = tuple[HandoverPlannedReplacement, ...]
type ProjectedReplacementDispositions = tuple[HandoverReplacementDisposition, ...]


@dataclass(frozen=True, slots=True)
class ProjectedReplacements:
    planned_replacements: ProjectedPlannedReplacements
    replacement_dispositions: ProjectedReplacementDispositions


def project_replacements(records: stored_state.ReplacementRecords) -> ProjectedReplacements:
    return ProjectedReplacements(
        tuple(
            HandoverPlannedReplacement(
                str(value.affected_item_id),
                value.relation_revision,
                str(value.replacement_item_id),
                value.replacement_cost,
                value.status,
                str(value.recorded_by),
                value.recorded_at.isoformat(),
                value.accepted_project_revision,
            )
            for value in records.planned_replacements
        ),
        tuple(
            HandoverReplacementDisposition(
                str(value.affected_item_id),
                value.relation_revision,
                value.rationale,
                value.accepted_cost,
                str(value.recorded_by),
                value.recorded_at.isoformat(),
                value.accepted_project_revision,
            )
            for value in records.dispositions
        ),
    )
