# Code generated by python -m codegen.replacements.compiler; DO NOT EDIT.

from pinboard.adapters.sqlite.errors import StorageError, StorageErrorCode
from pinboard.application import stored_state
from pinboard.domain import work_models
from pinboard.domain.identifiers import ItemId


def _replacement_revision(value: stored_state.StoredPlannedReplacement) -> int:
    return value.relation_revision


def validate_replacements(
    records: stored_state.ReplacementRecords,
    item_ids: set[ItemId],
    error_code: StorageErrorCode,
) -> None:
    replacements_by_item: dict[ItemId, list[stored_state.StoredPlannedReplacement]] = {}
    for replacement in records.planned_replacements:
        if replacement.affected_item_id not in item_ids or replacement.replacement_item_id not in item_ids:
            raise StorageError(error_code, "A planned replacement names an unknown work item.")
        replacements_by_item.setdefault(replacement.affected_item_id, []).append(replacement)
    indexed_replacements: dict[tuple[ItemId, int], stored_state.StoredPlannedReplacement] = {}
    for affected_item, replacements in replacements_by_item.items():
        ordered = sorted(replacements, key=_replacement_revision)
        if [value.relation_revision for value in ordered] != list(range(1, len(ordered) + 1)):
            raise StorageError(error_code, "Planned replacement revisions must be contiguous from revision 1.")
        indexed_replacements.update(((affected_item, value.relation_revision), value) for value in ordered)
    disposition_keys: set[tuple[ItemId, int]] = set()
    for disposition in records.dispositions:
        key = (disposition.affected_item_id, disposition.relation_revision)
        replacement = indexed_replacements.get(key)
        if replacement is None:
            raise StorageError(error_code, "A temporary-retention disposition names an unknown replacement revision.")
        if replacement.status != work_models.PlannedReplacementStatus.CURRENT:
            raise StorageError(error_code, "A temporary-retention disposition names a withdrawn replacement revision.")
        if disposition.accepted_cost != replacement.replacement_cost:
            raise StorageError(error_code, "A temporary-retention disposition must accept the exact replacement cost.")
        if key in disposition_keys:
            raise StorageError(error_code, "A replacement revision has duplicate temporary-retention dispositions.")
        disposition_keys.add(key)
