"""Compile the replacement declaration into explicit, statically checked Python."""

import argparse
import ast
import hashlib
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import NewType, assert_never, get_type_hints

import msgspec.inspect

from codegen.replacements.declaration import (
    REPLACEMENTS,
    ContiguousRevisions,
    Copy,
    CurrentReplacement,
    ExactCost,
    InvariantOperation,
    Isoformat,
    KnownItems,
    KnownReplacement,
    ProjectedField,
    ProjectionOperation,
    ReplacementFamily,
    Text,
    UniqueDisposition,
)
from pinboard.application import stored_state
from pinboard.domain import work_models

GENERATED_HEADER = "# Code generated by python -m codegen.replacements.compiler; DO NOT EDIT."
APPLICATION_OUTPUT = Path("src/pinboard/application/_generated/replacement_projection.py")
VALIDATION_OUTPUT = Path("src/pinboard/adapters/sqlite/_generated/replacement_validation.py")
DECLARATION_SOURCE = Path("codegen/replacements/declaration.py")
COMPILER_SOURCE = Path("codegen/replacements/compiler.py")
REPLACEMENT_SOURCE = Path("src/pinboard/application/stored_state.py")
GENERATE_COMMAND = "uv run --locked python -m codegen.replacements.compiler"
CHECK_COMMAND = f"{GENERATE_COMMAND} --check"
type SourceLeafType = (
    msgspec.inspect.IntType | msgspec.inspect.StrType | msgspec.inspect.EnumType | msgspec.inspect.DateTimeType
)


class DeclarationError(ValueError):
    """The replacement declaration does not cover its discovered source shape."""


@dataclass(frozen=True, slots=True)
class SourceField:
    name: str
    type: SourceLeafType
    annotation_identity: str


@dataclass(frozen=True, slots=True)
class SourceCollection:
    source: str
    row_identity: str
    fields: tuple[SourceField, ...]


def _qualified_annotation_name(annotation: type | NewType) -> str:
    name = annotation.__name__ if isinstance(annotation, NewType) else annotation.__qualname__
    return f"{annotation.__module__}.{name}"


def _validated_projection_operation(
    operation: ProjectionOperation | InvariantOperation,
    path: str,
) -> ProjectionOperation:
    if isinstance(operation, (Copy, Text, Isoformat)):
        return operation
    raise DeclarationError(
        f"replacement family: unsupported projection operation at {path}; use Copy, Text, or Isoformat"
    )


def _validated_invariant_operation(
    operation: ProjectionOperation | InvariantOperation,
    path: str,
    role: int,
) -> InvariantOperation:
    if isinstance(
        operation,
        (KnownItems, ContiguousRevisions, KnownReplacement, CurrentReplacement, ExactCost, UniqueDisposition),
    ):
        return operation
    raise DeclarationError(
        f"replacement family: unsupported invariant operation at {path} role {role}; use a declared invariant operation"
    )


def _source_collections(family: ReplacementFamily) -> tuple[SourceCollection, ...]:
    root = msgspec.inspect.type_info(family.source)
    if not isinstance(root, msgspec.inspect.DataclassType):
        raise DeclarationError("replacement family: source root must be a dataclass")
    collections: list[SourceCollection] = []
    for field in root.fields:
        if not isinstance(field.type, msgspec.inspect.VarTupleType):
            raise DeclarationError(
                f"replacement family: source path {family.source.__name__}.{field.name} must be a tuple of dataclasses"
            )
        row = field.type.item_type
        if not isinstance(row, msgspec.inspect.DataclassType):
            raise DeclarationError(
                f"replacement family: source path {family.source.__name__}.{field.name} must be a tuple of dataclasses"
            )
        try:
            annotations = get_type_hints(row.cls, include_extras=True)
        except (NameError, TypeError) as error:
            raise DeclarationError(
                f"replacement family: cannot resolve source annotations at {family.source.__name__}.{field.name}"
            ) from error
        leaves: list[SourceField] = []
        for leaf in row.fields:
            if not isinstance(
                leaf.type,
                (
                    msgspec.inspect.IntType,
                    msgspec.inspect.StrType,
                    msgspec.inspect.EnumType,
                    msgspec.inspect.DateTimeType,
                ),
            ):
                raise DeclarationError(
                    f"replacement family: unsupported source leaf {family.source.__name__}.{field.name}.{leaf.name}"
                )
            annotation = annotations.get(leaf.name)
            if not isinstance(annotation, (type, NewType)):
                raise DeclarationError(
                    f"replacement family: unsupported source annotation "
                    f"{family.source.__name__}.{field.name}.{leaf.name}"
                )
            leaves.append(SourceField(leaf.name, leaf.type, _qualified_annotation_name(annotation)))
        collections.append(
            SourceCollection(
                field.name,
                _qualified_annotation_name(row.cls),
                tuple(leaves),
            )
        )
    return tuple(collections)


def _source_shape_fingerprint(collections: tuple[SourceCollection, ...]) -> str:
    shape = "\n".join(
        (
            f"{collection.source}:{collection.row_identity}:"
            + ",".join(f"{field.name}:{field.annotation_identity}" for field in collection.fields)
        )
        for collection in collections
    )
    return hashlib.sha256(shape.encode()).hexdigest()


def _source_row_reference(collection: SourceCollection) -> str:
    module_prefix = f"{stored_state.__name__}."
    if collection.row_identity.startswith(module_prefix):
        return f"stored_state.{collection.row_identity.removeprefix(module_prefix)}"
    return collection.row_identity


def _validated_collections(family: ReplacementFamily) -> tuple[SourceCollection, ...]:
    discovered = _source_collections(family)
    discovered_roots = tuple(value.source for value in discovered)
    declared_roots = tuple(value.source for value in family.collections)
    if declared_roots != discovered_roots:
        raise DeclarationError(
            "replacement family: collection dispositions differ from discovered fields; "
            f"expected {discovered_roots!r}, declared {declared_roots!r}"
        )
    targets = tuple(value.target for value in family.collections)
    if len(set(targets)) != len(targets):
        raise DeclarationError(f"replacement family: duplicate collection targets {targets!r}")
    for source, declaration in zip(discovered, family.collections, strict=True):
        if not declaration.target.isidentifier():
            raise DeclarationError(
                f"replacement family: collection target {declaration.target!r} must be a Python identifier"
            )
        if not declaration.target_row.isidentifier() or not declaration.target_row.startswith("_"):
            raise DeclarationError(
                f"replacement family: generated row {declaration.target_row!r} must be a private Python identifier"
            )
        discovered_fields = tuple(value.name for value in source.fields)
        declared_fields = tuple(value.source for value in declaration.fields)
        if declared_fields != discovered_fields:
            raise DeclarationError(
                f"replacement family: field dispositions differ at "
                f"{family.source.__name__}.{source.source}; "
                f"expected {discovered_fields!r}, declared {declared_fields!r}"
            )
        for field in declaration.fields:
            _validated_projection_operation(
                field.operation,
                f"{family.source.__name__}.{source.source}.{field.source}",
            )
        if not declaration.invariants:
            raise DeclarationError(
                f"replacement family: invariant-role disposition missing at {family.source.__name__}.{source.source}"
            )
        for role, operation in enumerate(declaration.invariants, start=1):
            _validated_invariant_operation(
                operation,
                f"{family.source.__name__}.{source.source}",
                role,
            )
        tuple(_operation_name(operation) for operation in declaration.invariants)
    return discovered


def _target_alias(target: str) -> str:
    return "Projected" + "".join(part.title() for part in target.split("_"))


def _validate_private_row_imports(family: ReplacementFamily, source_root: Path) -> None:
    private_rows = frozenset(collection.target_row for collection in family.collections)
    generated_output = source_root / APPLICATION_OUTPUT.relative_to("src")
    for path in sorted(source_root.rglob("*.py")):
        if path == generated_output:
            continue
        module = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(module):
            match node:
                case ast.Name(id=symbol) | ast.Attribute(attr=symbol) | ast.alias(name=symbol):
                    if symbol in private_rows:
                        raise DeclarationError(
                            f"replacement family: private generated row symbol {symbol} used by {path.as_posix()}"
                        )
                case _:
                    pass


def _operation_name(operation: InvariantOperation) -> str:
    match operation:
        case KnownItems():
            return "known-items"
        case ContiguousRevisions():
            return "contiguous-revisions"
        case KnownReplacement():
            return "known-replacement"
        case CurrentReplacement():
            return "current-replacement"
        case ExactCost():
            return "exact-cost"
        case UniqueDisposition():
            return "unique-disposition"
        case _ as unreachable:
            assert_never(unreachable)


def _require_fields(path: str, available: tuple[str, ...], required: tuple[str, ...]) -> None:
    missing = tuple(field for field in required if field not in available)
    if missing:
        raise DeclarationError(f"replacement family: invariant at {path} names unknown fields {missing!r}")


def _annotation(operation: ProjectionOperation, source: SourceField) -> str:
    match operation:
        case Text() | Isoformat():
            return "str"
        case Copy():
            if isinstance(source.type, msgspec.inspect.IntType):
                return "int"
            if isinstance(source.type, msgspec.inspect.StrType):
                return "str"
            if (
                isinstance(source.type, msgspec.inspect.EnumType)
                and source.type.cls is work_models.PlannedReplacementStatus
            ):
                return "work_models.PlannedReplacementStatus"
            raise DeclarationError(
                f"replacement family: Copy has no generated annotation for source field {source.name}"
            )
        case _ as unreachable:
            assert_never(unreachable)


def _expression(operation: ProjectionOperation, source_field: str) -> str:
    match operation:
        case Copy():
            return f"value.{source_field}"
        case Text():
            return f"str(value.{source_field})"
        case Isoformat():
            return f"value.{source_field}.isoformat()"
        case _ as unreachable:
            assert_never(unreachable)


def _row_class(
    name: str,
    fields: tuple[ProjectedField, ...],
    source_fields: tuple[SourceField, ...],
) -> list[str]:
    lines = [f"class {name}(msgspec.Struct, frozen=True, forbid_unknown_fields=True):"]
    lines.extend(
        f"    {field.target}: {_annotation(field.operation, source)}"
        for field, source in zip(fields, source_fields, strict=True)
    )
    return lines


def render_application(family: ReplacementFamily) -> str:
    discovered = _validated_collections(family)
    first, second = family.collections
    first_source, second_source = discovered
    lines = [
        GENERATED_HEADER,
        f"# Source shape: sha256:{_source_shape_fingerprint(discovered)}",
        "",
        "from dataclasses import dataclass",
        "",
        "import msgspec",
        "",
        "from pinboard.application import stored_state",
        "from pinboard.domain import work_models",
        "",
        "",
        *_row_class(first.target_row, first.fields, first_source.fields),
        "",
        "",
        *_row_class(second.target_row, second.fields, second_source.fields),
        "",
        "",
        f"type {_target_alias(first.target)} = tuple[{first.target_row}, ...]",
        f"type {_target_alias(second.target)} = tuple[{second.target_row}, ...]",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class ProjectedReplacements:",
        *(f"    {collection.target}: {_target_alias(collection.target)}" for collection in family.collections),
        "",
        "",
        "def project_replacements(records: stored_state.ReplacementRecords) -> ProjectedReplacements:",
        "    return ProjectedReplacements(",
    ]
    for collection in family.collections:
        lines.extend(
            [
                f"        {collection.target}=tuple(",
                f"            {collection.target_row}(",
                *(f"                {_expression(field.operation, field.source)}," for field in collection.fields),
                "            )",
                f"            for value in records.{collection.source}",
                "        ),",
            ]
        )
    lines.extend(["    )", ""])
    return "\n".join(lines)


def render_validation(family: ReplacementFamily) -> str:
    discovered = _validated_collections(family)
    planned, dispositions = family.collections
    planned_source, disposition_source = discovered
    planned_fields = tuple(field.name for field in planned_source.fields)
    disposition_fields = tuple(field.name for field in disposition_source.fields)
    planned_row = _source_row_reference(planned_source)
    match planned.invariants:
        case (
            KnownItems(fields=item_fields, message=unknown_item_message),
            ContiguousRevisions(
                item_field=item_field,
                revision_field=revision_field,
                message=revision_message,
            ),
        ):
            _require_fields(planned.source, planned_fields, (*item_fields, item_field, revision_field))
        case _:
            roles = tuple(_operation_name(operation) for operation in planned.invariants)
            raise DeclarationError(
                f"replacement family: {planned.source} invariant roles must be "
                f"('known-items', 'contiguous-revisions'), declared {roles!r}"
            )
    match dispositions.invariants:
        case (
            KnownReplacement(
                item_field=disposition_item_field,
                revision_field=disposition_revision_field,
                message=unknown_replacement_message,
            ),
            CurrentReplacement(status_field=status_field, message=withdrawn_message),
            ExactCost(
                disposition_field=disposition_cost_field,
                replacement_field=replacement_cost_field,
                message=cost_message,
            ),
            UniqueDisposition(message=duplicate_message),
        ):
            _require_fields(
                dispositions.source,
                disposition_fields,
                (disposition_item_field, disposition_revision_field, disposition_cost_field),
            )
            _require_fields(planned.source, planned_fields, (status_field, replacement_cost_field))
        case _:
            roles = tuple(_operation_name(operation) for operation in dispositions.invariants)
            raise DeclarationError(
                f"replacement family: {dispositions.source} invariant roles must be "
                "('known-replacement', 'current-replacement', 'exact-cost', 'unique-disposition'), "
                f"declared {roles!r}"
            )
    lines = [
        GENERATED_HEADER,
        f"# Source shape: sha256:{_source_shape_fingerprint(discovered)}",
        "",
        "from pinboard.adapters.sqlite.errors import StorageError, StorageErrorCode",
        "from pinboard.application import stored_state",
        "from pinboard.domain import work_models",
        "from pinboard.domain.identifiers import ItemId",
        "",
        "",
        f"def _replacement_revision(value: {planned_row}) -> int:",
        f"    return value.{revision_field}",
        "",
        "",
        "def validate_replacements(",
        "    records: stored_state.ReplacementRecords,",
        "    item_ids: set[ItemId],",
        "    error_code: StorageErrorCode,",
        ") -> None:",
        f"    replacements_by_item: dict[ItemId, list[{planned_row}]] = {{}}",
        f"    for replacement in records.{planned.source}:",
        "        " + "if " + " or ".join(f"replacement.{field} not in item_ids" for field in item_fields) + ":",
        f"            raise StorageError(error_code, {json.dumps(unknown_item_message)})",
        f"        replacements_by_item.setdefault(replacement.{item_field}, []).append(replacement)",
        f"    indexed_replacements: dict[tuple[ItemId, int], {planned_row}] = {{}}",
        "    for affected_item, replacements in replacements_by_item.items():",
        "        ordered = sorted(replacements, key=_replacement_revision)",
        f"        if [value.{revision_field} for value in ordered] != list(range(1, len(ordered) + 1)):",
        f"            raise StorageError(error_code, {json.dumps(revision_message)})",
        f"        indexed_replacements.update(((affected_item, value.{revision_field}), value) for value in ordered)",
        "    disposition_keys: set[tuple[ItemId, int]] = set()",
        f"    for disposition in records.{dispositions.source}:",
        f"        key = (disposition.{disposition_item_field}, disposition.{disposition_revision_field})",
        "        replacement = indexed_replacements.get(key)",
        "        if replacement is None:",
        f"            raise StorageError(error_code, {json.dumps(unknown_replacement_message)})",
        f"        if replacement.{status_field} != work_models.PlannedReplacementStatus.CURRENT:",
        f"            raise StorageError(error_code, {json.dumps(withdrawn_message)})",
        f"        if disposition.{disposition_cost_field} != replacement.{replacement_cost_field}:",
        f"            raise StorageError(error_code, {json.dumps(cost_message)})",
        "        if key in disposition_keys:",
        f"            raise StorageError(error_code, {json.dumps(duplicate_message)})",
        "        disposition_keys.add(key)",
        "",
    ]
    return "\n".join(lines)


def _write_generated_output(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _source_shape_identity(content: str) -> str | None:
    return next((line for line in content.splitlines() if line.startswith("# Source shape: ")), None)


def _check_generated_outputs(outputs: tuple[tuple[Path, str], ...]) -> bool:
    mismatches = tuple(
        (path, content) for path, content in outputs if not path.exists() or path.read_text(encoding="utf-8") != content
    )
    if not mismatches:
        return True

    paths = tuple(str(path) for path, _content in mismatches)
    print(
        "replacement family: generated bytes differ from compiler output; "
        f"expected byte-for-byte equality, observed mismatches at {paths!r}",
        file=sys.stderr,
    )
    source_identity_changes: list[tuple[str, str, str]] = []
    for path, expected in mismatches:
        if not path.exists():
            continue
        expected_identity = _source_shape_identity(expected)
        observed_identity = _source_shape_identity(path.read_text(encoding="utf-8"))
        if expected_identity is not None and observed_identity is not None and expected_identity != observed_identity:
            source_identity_changes.append((str(path), expected_identity, observed_identity))
    if source_identity_changes:
        print(
            "replacement family: source-shape identity changed; "
            f"expected and observed fingerprints {source_identity_changes!r}. "
            f"Confirm intent at {REPLACEMENT_SOURCE} before regeneration.",
            file=sys.stderr,
        )
    print(
        f"Authoritative inputs: {REPLACEMENT_SOURCE}, {DECLARATION_SOURCE}, and {COMPILER_SOURCE}; "
        "do not edit generated Python.",
        file=sys.stderr,
    )
    print(f"Regenerate: {GENERATE_COMMAND}", file=sys.stderr)
    print(f"Next check: {CHECK_COMMAND}", file=sys.stderr)
    return False


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        _validate_private_row_imports(REPLACEMENTS, Path("src"))
        application_content = render_application(REPLACEMENTS)
        validation_content = render_validation(REPLACEMENTS)
    except DeclarationError as error:
        print(error, file=sys.stderr)
        print(
            f"Authoritative inputs: {REPLACEMENT_SOURCE}, {DECLARATION_SOURCE}, and {COMPILER_SOURCE}; "
            "correct the named relationship there, not in generated Python.",
            file=sys.stderr,
        )
        print(f"Next check: {CHECK_COMMAND}", file=sys.stderr)
        return 1
    outputs = ((APPLICATION_OUTPUT, application_content), (VALIDATION_OUTPUT, validation_content))
    if args.check:
        return 0 if _check_generated_outputs(outputs) else 1
    for path, content in outputs:
        _write_generated_output(path, content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
