import argparse
from collections.abc import Mapping, Sequence
from pathlib import Path

from . import brief, database, handover, journey, layers, product, review_loop
from .model import DAY_PALETTE, NIGHT_PALETTE, Diagram, render_svg

OUTPUT_PATHS = {
    "guide": Path("HOW_IT_WORKS.md"),
    "product": Path("assets/how-it-works/product.svg"),
    "layers": Path("assets/how-it-works/layers.svg"),
    "journey": Path("assets/how-it-works/journey.svg"),
    "database": Path("assets/how-it-works/database.svg"),
    "handover": Path("assets/how-it-works/handover.svg"),
    "brief": Path("assets/how-it-works/brief.svg"),
    "review-loop": Path("assets/how-it-works/review-loop.svg"),
}

DARK_OUTPUT_PATHS = {
    slug: path.with_stem(f"{path.stem}-dark") for slug, path in OUTPUT_PATHS.items() if path.suffix == ".svg"
}


def _picture(slug: str, alt: str) -> str:
    day_path = OUTPUT_PATHS[slug].as_posix()
    night_path = DARK_OUTPUT_PATHS[slug].as_posix()
    return f'''<picture>
  <source media="(prefers-color-scheme: dark)" srcset="{night_path}">
  <img src="{day_path}" alt="{alt}">
</picture>'''


def _guide() -> str:
    return f"""<!-- Generated by docs.how_it_works from executable seeds. Do not edit this file directly. -->

# How Pinboard works

Pinboard keeps long-running coding-agent work attached to the decisions that shaped it. It adds a repository-local record of proposed ideas, accepted work, implementation attempts, and review evidence without asking you to maintain a parallel ticket system.

For a short disposable change, working directly with a coding agent is often enough. Pinboard becomes useful when work crosses conversations, interruptions, reviewers, or parallel tasks and the latest chat is no longer a reliable account of why the code looks the way it does.

## One accepted direction anchors the loop

A coding agent already works through interpretation: it reads a request, changes the repository, reviews the result, and turns findings into another pass. As the loop grows, a plausible implementation detail or reviewer suggestion can quietly become the new target.

{_picture("review-loop", "An ordinary coding-agent implementation and review loop beside the same loop anchored by one accepted Pinboard brief, exact candidate, and evidence")}

Pinboard anchors that loop to one accepted direction. The implementer and a separate reviewer work from the same brief and the same candidate. Review can still find that the brief, implementation, or evidence is wrong, but the correction stays attached to an explicit decision instead of whichever message happens to be most recent.

The human still decides what belongs in the product, which tradeoffs are acceptable, and what should happen to reviewed repository changes. Pinboard preserves those decisions and returns material choices in ordinary language.

## The brief makes the agreement inspectable

Before implementation, Pinboard turns accepted direction into a structured brief. It separates the desired outcome from scope, exclusions, compatibility constraints, evidence, verification, and work deliberately left for later. Larger changes also name the project authorities and relationships the implementation and review must preserve.

{_picture("brief", "The canonical work brief organized into artifact identity, accepted scope, whole-work definition, and a checkpoint containing criteria, architecture impact, reviewed authorities, contracts, coverage, lifecycle distinctions, verification, and deferrals")}

The structure prevents important kinds of information from disappearing into a paragraph. It does not decide what the project should want or prove that every claim is true. People and coding agents still interpret the evidence; Pinboard checks that they are discussing the same accepted scope and that required distinctions have not been omitted.

Assurance follows that accepted product evidence. A defect against promised behavior remains blocking. A broader security, compatibility, durability, or platform guarantee does not become mandatory merely because an agent can imagine it.

## Work survives its current execution

A **work item** is the durable project decision. An **attempt** is one execution of that work. Keeping them separate allows the decision to survive a pause, correction, replacement worker, or later revision without treating every execution detail as part of the product request.

{_picture("product", "A work item lifecycle above the legal branches of an active attempt, with related facts shown separately")}

Ideas can be preserved before they are accepted or scheduled. Accepted work can wait for dependencies, move through implementation and review, pause at a useful checkpoint, return for correction, continue, or finish. A proposed replacement remains a related decision rather than becoming a hidden state: Pinboard keeps obsolete work from advancing until the human chooses whether to replace it or retain it temporarily.

Across those paths, four guarantees stay constant:

- **Intent survives conversations.** Later work can continue from accepted scope and evidence instead of reconstructing intent from chat history.
- **Only the current worker may act.** Replaced or expired execution authority cannot apply an earlier decision after ownership changes.
- **Review concerns one candidate.** Findings and acceptance stay bound to the exact result that was examined.
- **Authoritative changes are atomic.** A rejected or failed transition leaves the previous ledger intact; repairable views cannot silently rewrite accepted state.

## One change moves from decision to evidence

The ordinary journey has three parts: select the current accepted work, decide against current facts, then commit and present the result.

{_picture("journey", "An ordinary preparation start selecting the current definition and claim operation against locked state, then committing, refreshing, and presenting it")}

Preparation preserves the accepted meaning and the sources most likely to challenge it. Implementation reads that brief, follows the concrete impact through the repository, and records one candidate with its evidence. A separate reviewer checks the request as well as the change, widens the investigation when a changed relationship exposes another owner, and returns findings to the same attempt.

If accepted direction changes late, Pinboard does not reinterpret the old candidate as satisfying the new request. The complete definition and brief are replaced before another candidate and review. If work pauses or a worker disappears, the same attempt can resume from its accepted Git lineage and recorded evidence without retelling the project history.

The extra steps make a first delivery slower. Their return appears when the work needs another revision, conversation, reviewer, or task: the decision, implementation, and evidence remain connected.

## The repository keeps the memory

Pinboard stores project coordination data beside the repository. The relational ledger groups current work, accepted scope and dependencies, discoveries, immutable knowledge, current execution authority, and history.

{_picture("database", "Six groups of SQLite tables showing current work, scope, discovery, durable knowledge, mutation ownership, and history")}

SQLite is the authority. Accepted briefs, results, and reviews are immutable artifacts referenced by that ledger. Human-readable Markdown views are replaceable projections for inspection; if refreshing one fails, the accepted transaction remains authoritative and the view can be rebuilt.

This local record supports recovery and review, but it is not a defense against a hostile user with the same filesystem access. Pinboard is designed for one trusted local developer authority and for failures such as stale actions, invalid input, interrupted publication, and ordinary concurrency.

## Handover carries facts, not control

When work must move to another tool, Pinboard can assemble the admitted work, accepted definitions, attempts, proposals, relationships, decisions, and verified evidence into one portable package.

{_picture("handover", "Exported Pinboard project facts and verified artifacts becoming one portable JSON package while live authority stays local")}

The package captures one coherent project revision. It does not export live worker authority, mutate Pinboard, choose how the receiving tool represents the facts, or write into that tool. A human or the receiving system owns that mapping.

## Responsibility stays visible

Pinboard keeps product decisions, operation sequencing, persistence, and external presentation in four package layers.

{_picture("layers", "Four package layers showing interfaces, application, domain, and adapters, connected by package dependencies")}

Every arrow means “may depend on.” Interfaces make outside input exact and present results. Application code coordinates complete operations through explicit capabilities. The domain decides legality without reading files or issuing SQL. Adapters store and recover accepted facts without deciding workflow policy.

That separation is why a storage failure cannot redefine a product decision, a renderer cannot become the source of truth, and an interface cannot silently invent lifecycle policy.

For installation and the product overview, return to the [README](README.md). Maintainers can continue with the exact [architecture map](ARCHITECTURE.md) and the [design principles](DESIGN_PRINCIPLES.md).

---

<sub>This guide and its seven SVG diagrams are generated from the executable seeds in <code>docs/how_it_works/</code>. Edit the seeds and regenerate the outputs; do not edit this file directly.</sub>
"""


def _output_path(item: tuple[Path, str]) -> str:
    return item[0].as_posix()


def build_outputs(root: Path) -> dict[Path, str]:
    """Validate the complete guide and raise if no coherent output set can be built."""

    product.validate()
    layers.validate(root)
    journey.validate()
    database.validate(root)
    handover.validate()
    brief.validate()
    review_loop.validate()
    diagrams: tuple[Diagram, ...] = (
        product.DIAGRAM,
        layers.DIAGRAM,
        journey.DIAGRAM,
        database.DIAGRAM,
        handover.DIAGRAM,
        brief.DIAGRAM,
        review_loop.DIAGRAM,
    )
    outputs: dict[Path, str] = {}
    for diagram in diagrams:
        outputs[OUTPUT_PATHS[diagram.slug]] = render_svg(diagram, DAY_PALETTE)
        outputs[DARK_OUTPUT_PATHS[diagram.slug]] = render_svg(diagram, NIGHT_PALETTE)
    outputs[OUTPUT_PATHS["guide"]] = _guide()
    return dict(sorted(outputs.items(), key=_output_path))


def stale_outputs(root: Path, outputs: Mapping[Path, str]) -> tuple[Path, ...]:
    stale: list[Path] = []
    for relative_path, expected in outputs.items():
        path = root / relative_path
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(relative_path)
    return tuple(stale)


def write_outputs(root: Path, outputs: Mapping[Path, str]) -> None:
    for relative_path, content in outputs.items():
        path = root / relative_path
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main(arguments: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the visitor-facing How Pinboard works guide.")
    parser.add_argument("--check", action="store_true", help="fail when committed outputs are stale")
    options = parser.parse_args(arguments)
    root = Path(__file__).resolve().parents[2]
    outputs = build_outputs(root)
    if options.check:
        stale = stale_outputs(root, outputs)
        if stale:
            print("generated visitor guide differs from its source:")
            for path in stale:
                print(f"  {path}")
            print("regenerate and commit: uv run --locked python -m docs.how_it_works.render")
            return 1
        print("generated visitor guide is current")
        return 0
    write_outputs(root, outputs)
    print(f"generated {len(outputs)} visitor-guide files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
