import argparse
from collections.abc import Mapping, Sequence
from pathlib import Path

from . import brief, database, handover, journey, layers, product, review_loop
from .model import DAY_PALETTE, NIGHT_PALETTE, Diagram, render_svg

OUTPUT_PATHS = {
    "guide": Path("HOW_IT_WORKS.md"),
    "product": Path("assets/how-it-works/product.svg"),
    "layers": Path("assets/how-it-works/layers.svg"),
    "journey": Path("assets/how-it-works/journey.svg"),
    "database": Path("assets/how-it-works/database.svg"),
    "handover": Path("assets/how-it-works/handover.svg"),
    "brief": Path("assets/how-it-works/brief.svg"),
    "review-loop": Path("assets/how-it-works/review-loop.svg"),
}

DARK_OUTPUT_PATHS = {
    slug: path.with_stem(f"{path.stem}-dark") for slug, path in OUTPUT_PATHS.items() if path.suffix == ".svg"
}


def _picture(slug: str, alt: str) -> str:
    day_path = OUTPUT_PATHS[slug].as_posix()
    night_path = DARK_OUTPUT_PATHS[slug].as_posix()
    return f'''<picture>
  <source media="(prefers-color-scheme: dark)" srcset="{night_path}">
  <img src="{day_path}" alt="{alt}">
</picture>'''


def _guide() -> str:
    return f"""<!-- Generated by docs.how_it_works from executable seeds. Do not edit this file directly. -->

# How Pinboard works

Pinboard adds one repository-local ledger of proposals, accepted work, attempts, and evidence to long-running Codex work. It preserves what the human requested, what an agent proposed, what the project accepted, which execution is acting on it, and what evidence a reviewer can trust later.

For one short, isolated change, Codex already supplies the planning, implementation, testing, and review loop. Pinboard adds deliberate steps when the project must remain coherent across discoveries, parallel tasks, interruptions, and later iterations.

## Contents

- [Workflow at a glance](#workflow-at-a-glance)
- [Why Pinboard changes the Codex loop](#why-pinboard-changes-the-codex-loop)
  - [Codex already iterates](#codex-already-iterates)
  - [Strict shape, semantic judgment](#strict-shape-semantic-judgment)
- [The product model](#the-product-model)
  - [Work items and attempts](#work-items-and-attempts)
  - [What every transition preserves](#what-every-transition-preserves)
- [Command stories](#command-stories)
  - [Read, validate, initialize, and repair](#read-validate-initialize-and-repair)
  - [Follow one change](#follow-one-change)
  - [Borrow coordination for one shared change](#borrow-coordination-for-one-shared-change)
  - [Carry the project into another tool](#carry-the-project-into-another-tool)
- [Under the surface](#under-the-surface)
  - [The durable memory underneath](#the-durable-memory-underneath)
  - [Where responsibilities live](#where-responsibilities-live)

## Workflow at a glance

The practical path is short enough to tell without the data model:

1. **Preserve a discovery.** Intake records its trigger, evidence, hypothesis, and likely effect without changing current priority or adding it to the active feature.
2. **Accept exact work.** Coordination decides which proposal belongs in the product, records the complete current definition, and keeps unaccepted ideas visibly separate.
3. **Prepare the brief.** A renewable preparation claim reserves that exact ready definition while one canonical brief is compiled and reviewed. The item does not become active yet.
4. **Implement that brief.** Activation binds the accepted brief to one attempt. The worker claims the attempt, rereads the brief, and changes the ordinary repository in its assigned checkout.
5. **Reconcile late direction.** Before candidate presentation or acceptance, the owning task accounts for user direction and repository changes since the accepted brief. A changed product target replaces the complete definition and brief, invalidates stale candidate or review identity, and requires another exact candidate and review.
6. **Submit one candidate.** The worker records the exact candidate and its evidence. Submission protects that identity instead of asking review to infer what changed from the latest files.
7. **Review the same decision.** A separate Codex reviewer compares that candidate with the same accepted brief and returns it for correction, accepts a checkpoint, or continues the attempt. The human-facing task then asks the human to choose repository disposition and confirm completion before the work becomes terminal.
8. **Recover without retelling.** Pause and block preserve the attempt and its evidence. Resume requires a brief matching the current definition, so a later task cannot quietly continue obsolete scope.

This normally takes more turns than asking Codex to implement and review a prompt directly. The extra work is the mechanism: discoveries remain proposals, implementation rereads accepted scope, and review receives the exact brief and candidate. Pinboard trades first-delivery speed for a durable boundary between the product you accepted and the plausible additions an agent could otherwise accumulate.

## Why Pinboard changes the Codex loop

### Codex already iterates

A coding harness turns prose into code through interpretation. An implementer reads the request and repository, produces a change, and a reviewer interprets the request and result again. Review findings become new prose for another implementation pass. Codex already supplies this productive back-and-forth.

When the only shared target is the evolving conversation and latest diff, each pass can give new weight to an implementation detail or useful reviewer suggestion. That does not make every untracked loop drift. The risk grows when work crosses more turns, tasks, interruptions, and adjacent discoveries.

{_picture("review-loop", "An ordinary Codex implementation and review loop beside the same loop anchored by one accepted Pinboard brief, exact candidate, and evidence")}

Pinboard gives both sides a stable reference. The implementer rereads the accepted brief, submits one exact candidate with evidence, and a separate reviewer receives that same brief and candidate. Correction returns to the same attempt, with blocking findings tied to accepted scope, criteria, or reviewed project authority. If later accepted direction changes the target, the old candidate and review no longer qualify for wrap-up: the complete definition and brief are replaced before another exact candidate and review. The loop still depends on LLM and human judgment and can still be wrong; its corrections remain aimed at an explicit accepted target instead of whatever prose happens to be most recent.

### Strict shape, semantic judgment

**The brief is an information architecture, not a bag of prose.** Artifact identity and accepted-scope identity anchor the whole job. The work definition separates outcome, scope, non-goals, compatibility, provenance, testing, bootstrap, and remaining work. Its checkpoint then names the reviewable boundary and expands it into criteria, architecture impact, reviewed authorities, contracts, coverage, lifecycle distinctions, verification, and explicit deferrals. Those relationships tell an implementer what to build and give an independent reviewer the same map for challenging it.

{_picture("brief", "The canonical work brief organized into artifact identity, accepted scope, whole-work definition, and a checkpoint containing criteria, architecture impact, reviewed authorities, contracts, coverage, lifecycle distinctions, verification, and deferrals")}

**Code checks the envelope; humans and models interpret the meaning.** The canonical work brief is strict JSON and the sole semantic brief. Pinboard rejects unknown fields and cross-checks identities, references, coverage, and canonical bytes. It cannot prove that prose under `scope` is truly in scope or that a `non_goals` entry expresses the human's intent. The model interprets those meanings, the human accepts the product decision, and independent review challenges the compiled result. The schema makes distinct reasoning jobs difficult to omit and stable across stages without pretending to replace judgment.

**Project impact remains a judgment too.** Pinboard has no rule saying that a visitor-facing decision must also change a workflow guide or a durable design principle. Structured scope, provenance, reviewed authorities, and coverage help Codex reason toward affected surfaces without a hard-coded file map or an exhaustive reread. The model can still miss or invent a connection; human acceptance and independent review decide whether it is real. This is information architecture refined through experience, not a semantic consistency engine.

The rest of this guide moves from the product concepts a visitor encounters to representative command stories, then to the storage and package structure underneath.

## The product model

### Work items and attempts

A work item is the durable project decision. An attempt is one execution of that work. They move together while remaining separate: an item can survive interruption, correction, or a replacement worker without losing its identity or accepted scope.

{_picture("product", "A work item lifecycle above the legal branches of an active attempt, with related facts shown separately")}

**The main lifecycle stays familiar.** Intake becomes ready, active work enters review, and accepted work reaches a terminal outcome. Deferred, paused, and blocked work are optional branches. Review can request correction, pause at an accepted checkpoint, or accept the candidate and continue. The human-facing task reconciles later direction, presents the accepted candidate for a repository decision, and records terminal completion only after the human confirms that disposition. Completion can also be accepted directly from active work after the same reconciliation and confirmation.

**Recovery preserves the right identity.** Resume makes a retained attempt active, while an item without one becomes ready. Reopen returns deferred work to intake with new evidence. Continue is advisory: it confirms that active work proceeds without changing lifecycle state or accepting mutation input. The action record's stable `effect` field describes that lifecycle effect; it does not claim that a wider command such as dispatch performs no artifact I/O. Dispatch can publish or reuse review evidence while leaving lifecycle unchanged.

**Related facts are not extra states.** Proposal intake stores the original facts and creates same-identity `intake` work. Accept applies selected details to that item; merge supersedes it in favor of another; return keeps it in intake with a clarification reason; reject drops it. Accepted scope is the exact authorized revision an attempt uses. Mutation ownership records who may act now. A review candidate names the exact result under review, and evidence supports its acceptance.

### What every transition preserves

The lifecycle is accompanied by four guarantees:

- **Work survives conversations.** A later task can continue from accepted scope and evidence instead of reconstructing intent from chat history.
- **Mutation ownership is current.** An expired or replaced worker cannot apply an action it discovered earlier.
- **Review is about one candidate.** Correction, checkpoint acceptance, continuation, and terminal completion preserve different outcomes without changing which work they belong to.
- **Each authoritative change is atomic.** An accepted change updates its related facts and history together; a rejected or failed change leaves the previous ledger intact.

These guarantees explain why seemingly similar words remain distinct.

## Command stories

The command stories move from observation and repair to an ordinary mutation, temporary shared authority, and portable export.

### Read, validate, initialize, and repair

- **Inspect focused facts.** The command line decodes one exact leaf, root resolution selects the source checkout, shared repository, and work directory, and the interface samples time when lease expiry matters. Status uses fixed-size metadata and grouped counts; item, definition, artifact, and authority reads use exact keys; history is caller-bounded; overview and parallel preview use the live graph. Inspection neither reads accumulated unrelated history nor refreshes generated files or changes authority. `input-contract` is deliberately different: it describes static action semantics and payload shape from the selected action kind without opening project state.

- **Validate before repairing.** `status` is a bounded summary, not the full integrity check. `validate` intentionally runs whole-database integrity checks, verifies accepted brief content, every accepted artifact identity, and every replaceable generated view against complete stored state. Authoritative defects are errors; missing or stale generated views are warnings because SQLite and accepted artifacts remain the source of truth. Validation only reports. `views rebuild` separately derives and replaces every focus, per-item, per-attempt, and per-receipt history projection from complete state and verified brief content.

- **Initialize through a verified publication.** A new ledger is built and verified in a staging file before atomic publication, then receives its empty generated projection. A returning ledger is schema-checked before Pinboard reconciles only its own same-file publication residue and ensures its directories; it does not run integrity scans, inspect artifacts, or rebuild views. Both routes use explicit roots and one operation time and present the receipt. After a successful first initialization, the interface points once to the optional `$repository-readiness`, `$slop-cleanup`, and `$maintaining-agent-guidance` skills without running them or creating work. It may separately recommend one absent Codex long-task default; neither path writes configuration or claims to override trusted project settings. Resumed and failed initialization stay quiet, while unreadable or malformed user config suppresses only the setting recommendation.

- **Plan reviewed sources without opening the ledger.** `brief-sources` reads one strict manifest, selects whole files or unique Markdown headings from the chosen source checkout, rejects overlaps and oversized lines, assigns every selected byte to one ordered segment and batch, and presents the complete plan or one requested batch. It never edits the project.

### Follow one change

**Observe and resolve.** Acquiring a preparation claim begins when the command-line boundary decodes an exact acquisition command. The preparation interface observes stored context, then resolves the supplied coordination claim and lease details into one requested change. Observation can explain an absent claim, but it is not the authoritative state that approves the change.

**Decide and commit against locked facts.** The application opens the write transaction and selects the exact current facts required by that decision. A pure domain decision returns an accepted authority change or an expected rejection. The application projects acceptance into one focused mutation; SQLite writes only changed rows and returns the exact receipt plus compact affected facts for presentation and generated views. Rejection and stale guards are expected failures, infrastructure or programming failures remain exceptions, and every unsuccessful transaction rolls back.

{_picture("journey", "A preparation-authority request being decoded, observed, resolved, decided against locked state, committed, refreshed, and presented")}

**Refresh and present afterward.** A failed replaceable-view refresh can warn without undoing the authoritative commit. Commands consume the compact committed effect rather than independently reloading complete state. Transition commands present the exact revision returned by their own commit, even if another writer advances the ledger before presentation. The representative code repeats the same provenance story: observed facts become a requested change; the application owns locked facts, accepted decision, focused mutation, commit, and compact effect; exact refresh and presentation follow.

### Borrow coordination for one shared change

Some installed commands need temporary graph-wide authority without becoming its long-term owner. Close first builds its transition payload. Item revision first reads and validates the complete proposed definition. Coordination apply first reads the supplied bytes. Each then follows the same sequence:

1. **Acquire temporary authority.** The interface observes stored state and requests coordination in one authoritative SQLite transaction. A rejected acquisition stops the command without cleanup.
2. **Reread, select, and commit.** After acquisition, the interface rereads the retained lease, discovers the currently legal coordinator actions, selects the requested action, and only then decodes its matching payload. The product transition is decided and committed in a second atomic transaction.
3. **Release even after failure.** The interface attempts a third transaction whether the product transition succeeded, returned an expected rejection, or raised an exception. The three changes are not one transaction, and release is not guaranteed. If release fails after a successful transition, that transition remains committed and the temporary lease may remain active. A cleanup failure accompanies an expected rejection; an unexpected transition exception remains primary and receives any cleanup failure as a note.
4. **Refresh affected views.** Only a successful transition and release refresh the product transition's changed entity projections plus the exact acquisition, product-transition, and release receipt files. A warning leaves all authoritative commits stored for explicit `pinboard views rebuild`. Presentation identifies the product-transition revision, not the later release revision.

### Carry the project into another tool

Local continuity and external handover are different jobs. `pinboard handover --json` captures one ledger revision, projects the supported project facts from it, verifies every referenced accepted artifact against its recorded identity and bytes, and emits one revision-stamped portable JSON package only after the exported package is ready.

{_picture("handover", "Exported Pinboard project facts and verified artifacts becoming one portable JSON package while live authority stays local")}

The package carries admitted work, focus, accepted definitions, attempts, pending proposals, relationships, decisions, and accepted evidence without choosing how another system represents them. Live coordination, preparation claims, attempt leases, and their generations remain in Pinboard and are not exported. Handover changes no Pinboard state and does not choose or write to the receiving tool; a human or another tool owns that mapping.

## Under the surface

The final views explain what Pinboard retains and where the code assigns responsibility for changing it.

### The durable memory underneath

The relational ledger groups eighteen tables into six kinds of memory: current work, accepted scope and dependencies, discoveries, immutable knowledge, changing mutation ownership, and the history that connects them.

{_picture("database", "Six groups of SQLite tables showing current work, scope, discovery, durable knowledge, mutation ownership, and history")}

**Relational facts retain their history.** A work item survives attempts, and accepted versions preserve current scope and its revisions. Proposal evidence records why intake work was raised; freshness assumptions record which facts need another check. The original proposal remains attached to the work while disposition records its later accept, merge, return, or reject decision.

**Immutable artifacts enter through three paths:**

1. **Brief publication** strictly decodes and cross-validates the selected candidate, canonicalizes and publishes its bytes, and accepts the stable reference in SQLite without refreshing generated views. Activation or resume then selects that accepted brief and publishes its attempt projection.
2. **Dispatch preparation** validates the environment, optional prompt or review files, exact current action, accepted brief identity, and reviewed sources before choosing the local, existing-review, or new-review path. It may publish or reuse independent ready-review evidence by exact identity, renders the prompt, rechecks authority, and only then emits it. Dispatch prepares a prompt; it does not create a task. Declared permissions remain coordinator declarations, not grants enforced by Pinboard.
3. **Checkpoint acceptance** publishes the exact result and independent review, then atomically records the attempt result, accepted review evidence, lifecycle change, and receipt. Publication alone changes no lifecycle state; rejection or rollback preserves the previous relationships.

**Mutation ownership has three scopes:**

- A coordination lease may be borrowed for one shared scheduling or graph-wide change, then released.
- A preparation claim keeps an item ready while one task compiles and reviews its definition-bound brief; activation consumes the claim when it creates the attempt.
- An attempt lease identifies the task, host, and lease that own one implementation attempt. Generations fence older preparation and attempt owners after transfer or revocation, while unrelated item-scoped leases remain independent.

Project state holds the current revision. Committed history records each accepted input, outcome, and actor.

### Where responsibilities live

The package is split into four layers because each removes a different kind of ambiguity. The split keeps workflow policy out of storage and keeps external representations out of decisions.

{_picture("layers", "Four package layers showing interfaces, application, domain, and adapters, connected by package dependencies")}

Every arrow in this view means “may depend on.”

- **Interfaces** absorb command lines, JSON, project files, and human-readable output. A small exhaustive entry point routes exact commands; thematic interface modules own composition that needs concrete adapters.
- **Application code** requests purpose-specific stored facts and projects an accepted decision into one focused storage mutation with a compact post-commit effect.
- **The domain** decides legality as pure data.
- **Adapters** make accepted facts durable and recoverable.

These transformations prevent one layer from silently interpreting facts owned by another.

For installation and the product story, return to the [README](README.md). For contributor-facing ownership, storage boundaries, and representative command flows, continue to the [architecture map](ARCHITECTURE.md). The [design principles](DESIGN_PRINCIPLES.md) explain the method used to keep those boundaries explicit.

---

<sub>This guide and its SVG diagrams are generated from the executable seeds in <code>docs/how_it_works/</code>. The repository check proves that committed output is fresh and that the specific source relationships encoded by those seeds still hold.</sub>
"""


def _output_path(item: tuple[Path, str]) -> str:
    return item[0].as_posix()


def build_outputs(root: Path) -> dict[Path, str]:
    product.validate()
    layers.validate(root)
    journey.validate()
    database.validate(root)
    handover.validate()
    brief.validate()
    review_loop.validate()
    diagrams: tuple[Diagram, ...] = (
        product.DIAGRAM,
        layers.DIAGRAM,
        journey.DIAGRAM,
        database.DIAGRAM,
        handover.DIAGRAM,
        brief.DIAGRAM,
        review_loop.DIAGRAM,
    )
    outputs: dict[Path, str] = {}
    for diagram in diagrams:
        outputs[OUTPUT_PATHS[diagram.slug]] = render_svg(diagram, DAY_PALETTE)
        outputs[DARK_OUTPUT_PATHS[diagram.slug]] = render_svg(diagram, NIGHT_PALETTE)
    outputs[OUTPUT_PATHS["guide"]] = _guide()
    return dict(sorted(outputs.items(), key=_output_path))


def stale_outputs(root: Path, outputs: Mapping[Path, str]) -> tuple[Path, ...]:
    stale: list[Path] = []
    for relative_path, expected in outputs.items():
        path = root / relative_path
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(relative_path)
    return tuple(stale)


def write_outputs(root: Path, outputs: Mapping[Path, str]) -> None:
    for relative_path, content in outputs.items():
        path = root / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main(arguments: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the visitor-facing How Pinboard works guide.")
    parser.add_argument("--check", action="store_true", help="fail when committed outputs are stale")
    options = parser.parse_args(arguments)
    root = Path(__file__).resolve().parents[2]
    outputs = build_outputs(root)
    if options.check:
        stale = stale_outputs(root, outputs)
        if stale:
            print("generated visitor guide differs from its source:")
            for path in stale:
                print(f"  {path}")
            print("regenerate and commit: uv run --locked python -m docs.how_it_works.render")
            return 1
        print("generated visitor guide is current")
        return 0
    write_outputs(root, outputs)
    print(f"generated {len(outputs)} visitor-guide files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
