import argparse
from collections.abc import Mapping, Sequence
from pathlib import Path

from . import ambiguity_closure, brief, journey, product
from .model import DAY_PALETTE, NIGHT_PALETTE, Diagram, render_svg

OUTPUT_PATHS = {
    "guide": Path("HOW_IT_WORKS.md"),
    "ambiguity-closure": Path("assets/how-it-works/ambiguity-closure.svg"),
    "product": Path("assets/how-it-works/product.svg"),
    "journey": Path("assets/how-it-works/journey.svg"),
    "brief": Path("assets/how-it-works/brief.svg"),
}

DARK_OUTPUT_PATHS = {
    slug: path.with_stem(f"{path.stem}-dark") for slug, path in OUTPUT_PATHS.items() if path.suffix == ".svg"
}


def _picture(slug: str, alt: str) -> str:
    day_path = OUTPUT_PATHS[slug].as_posix()
    night_path = DARK_OUTPUT_PATHS[slug].as_posix()
    return f'''<picture>
  <source media="(prefers-color-scheme: dark)" srcset="{night_path}">
  <img src="{day_path}" alt="{alt}">
</picture>'''


def _guide() -> str:
    return f"""<!-- Generated by docs.how_it_works from executable seeds. Do not edit this file directly. -->

# How Pinboard works

Pinboard keeps long-running coding-agent work attached to the decisions that shaped it. It adds a repository-local record of accepted work, implementation attempts, and review evidence without asking you to maintain a parallel ticket system.

For a short disposable change, working directly with a coding agent is often enough. Pinboard becomes useful when work crosses conversations, interruptions, reviewers, or parallel tasks and the latest chat is no longer a reliable account of why the code looks the way it does.

## Ambiguity closes around one accepted brief

Work begins with structured intake and discussion, not an implementation prompt assembled from the latest message. The human and agent make the outcome, constraints, evidence, and material unknowns explicit enough to form an inspectable agreement.

{_picture("ambiguity-closure", "Structured intake and discussion becoming a reviewed brief that anchors implementation and exact-candidate review, with defects returning for correction and discoveries outside delegated authority returning to a human decision")}

The accepted brief anchors both implementation and review. Cross-boundary work receives an independent review of the brief before implementation; local work uses a lighter brief and skips that separate review. The worker then implements the accepted scope, verifies it, and submits one exact candidate with its evidence. A separate reviewer evaluates that candidate against the same brief.

Implementation defects return to the same attempt for bounded correction and another review. A discovery that changes product scope, architecture, compatibility, or another delegated boundary returns to the human. If the agreement changes, Pinboard replaces the complete definition and brief before affected implementation resumes; it does not reinterpret the old candidate as satisfying a new request.

The human still decides what belongs in the product, which tradeoffs are acceptable, and what happens to reviewed repository changes. Structure keeps those choices visible; it does not make them automatically correct.

## The brief makes delegation inspectable

Before implementation, Pinboard turns accepted direction into a strict structured brief. The artifact identifies the item, attempt, owner, branch, base revision, checkout, and exact accepted-scope revision and digest. Its whole-work definition records the outcome, scope, non-goals, compatibility, supported roots, provenance, testing strategy, bootstrap, and the mapping from accepted obligations to evidence.

{_picture("brief", "The canonical work brief organized into artifact identity, accepted scope, whole-work definition, and a checkpoint containing criteria, architecture impact, reviewed authorities, contracts, coverage, lifecycle distinctions, verification, and deferrals")}

Each checkpoint states its outcome, acceptance criteria, architecture impact, required verification, deferrals, and whether accepted work continues or terminates. A cross-boundary checkpoint also binds reviewed authorities, contracts, consumer coverage, and lifecycle distinctions. A local checkpoint is valid only while ownership, dependency direction, stored and wire identities, and independent consumers remain unchanged and one entry point exposes the complete change.

This structure gives an agent a bounded job and gives the reviewer the same checklist. It keeps exclusions, evidence limits, work deliberately deferred, and unresolved decisions from disappearing into prose. Pinboard validates shape, identity, references, and canonical bytes; people and language models still judge whether the facts and choices are sound.

### Agent actions stay explicit and bounded

The native MCP surface separates reading, authority, immutable publication, candidate observation, and lifecycle change. A few representative operations show how the brief governs the work:

- `proposal_create`, `brief_contract`, `brief_sources`, `brief_publish`, and `brief_review` preserve direction, construct the exact brief, select source evidence, and record independent brief findings.
- `actions` exposes only legal current operations and their exact payloads. `preparation_authority` and `attempt_authority` fence who may prepare or implement; `dispatch` publishes verified launch instructions without granting that authority.
- `artifact_verify` checks immutable accepted bytes. `candidate_observe` identifies the actual tracked working-tree candidate, and `review_job` binds that candidate, brief, result, and selected history into a separate reviewer launch.
- `attempt_inspect` exposes one attempt's current continuation. `candidate_restore` can restore its accepted candidate into an exact clean checkout, while `transition` alone applies a freshly discovered lifecycle mutation.

The complete surface also contains focused project and definition reads, priority and parallel planning, and status operations. The point is not the inventory: each operation has one advertised data scope and effect, so an agent cannot treat a convenient read, prompt publication, or stale receipt as mutation authority.

## Work survives its current execution

A **work item** is the durable project decision. An **attempt** is one execution of that work. Keeping them separate allows the decision to survive a pause, correction, replacement worker, or later revision without treating every execution detail as part of the product request.

{_picture("product", "A work item lifecycle above the legal branches of an active attempt, with related facts shown separately")}

Ideas can be preserved before they are accepted or scheduled. Accepted work can wait for dependencies, move through implementation and review, pause at a useful checkpoint, return for correction, continue, or finish. A proposed replacement remains a separate decision rather than silently changing the active target.

Across those paths, four guarantees stay constant:

- **Intent survives conversations.** Later work can continue from accepted scope and evidence instead of reconstructing intent from chat history.
- **Only the current worker may act.** Replaced or expired execution authority cannot apply an earlier decision after ownership changes.
- **Review concerns one candidate.** Findings and acceptance stay bound to the exact result that was examined.
- **Authoritative changes are atomic.** A rejected or failed transition leaves the previous ledger intact; repairable views cannot silently rewrite accepted state.

## The same workflow, viewed through the codebase

Starting a preparation claim through MCP is one representative path through the same design. The interface decodes an exact request and samples operation time. Application code opens the transaction, reads the current definition and authority facts, and selects the claim operation. A pure domain decision accepts or rejects that requested change without reading files or issuing SQL. The application projects an accepted decision into a targeted mutation; the SQLite adapter commits it, and the filesystem adapter refreshes replaceable views before the interface presents the result.

{_picture("journey", "An ordinary preparation claim moving from an exact MCP request through application orchestration and a pure domain decision to SQLite commit, replaceable view refresh, and a typed result")}

The separation preserves facts that the next agent can act on. A successful operation returns its receipt, effect, and changed surfaces. An expected rejection retains its code, observations, mismatches, retry disposition, and current conflict facts when present. A stale persistence guard remains distinct from a domain rejection, while infrastructure failures remain exceptions. If view refresh fails after commit, the SQLite result remains authoritative and the response identifies the repairable surface. The agent can therefore correct input, refresh an action, reacquire authority, repair a projection, or stop without inferring what happened from prose.

This operation is the opening workflow in code: exact input becomes an explicit requested change, one owner decides it, effects preserve the accepted facts, and presentation reports what happened. The boundaries matter because an accepted decision, a durable commit, and a human-readable projection are related but not interchangeable.

For installation and the product overview, return to the [README](README.md). Maintainers can continue with the exact [architecture map](ARCHITECTURE.md) and the [design principles](DESIGN_PRINCIPLES.md).

---

<sub>This guide and its four SVG diagrams are generated from the executable seeds in <code>docs/how_it_works/</code>. Edit the seeds and regenerate the outputs; do not edit this file directly.</sub>
"""


def _output_path(item: tuple[Path, str]) -> str:
    return item[0].as_posix()


def build_outputs() -> dict[Path, str]:
    """Validate the complete guide and raise if no coherent output set can be built."""

    ambiguity_closure.validate()
    product.validate()
    journey.validate()
    brief.validate()
    diagrams: tuple[Diagram, ...] = (
        ambiguity_closure.DIAGRAM,
        brief.DIAGRAM,
        product.DIAGRAM,
        journey.DIAGRAM,
    )
    outputs: dict[Path, str] = {}
    for diagram in diagrams:
        outputs[OUTPUT_PATHS[diagram.slug]] = render_svg(diagram, DAY_PALETTE)
        outputs[DARK_OUTPUT_PATHS[diagram.slug]] = render_svg(diagram, NIGHT_PALETTE)
    outputs[OUTPUT_PATHS["guide"]] = _guide()
    return dict(sorted(outputs.items(), key=_output_path))


def stale_outputs(root: Path, outputs: Mapping[Path, str]) -> tuple[Path, ...]:
    stale: list[Path] = []
    for relative_path, expected in outputs.items():
        path = root / relative_path
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(relative_path)
    return tuple(stale)


def write_outputs(root: Path, outputs: Mapping[Path, str]) -> None:
    for relative_path, content in outputs.items():
        path = root / relative_path
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main(arguments: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the visitor-facing How Pinboard works guide.")
    parser.add_argument("--check", action="store_true", help="fail when committed outputs are stale")
    options = parser.parse_args(arguments)
    root = Path(__file__).resolve().parents[2]
    outputs = build_outputs()
    if options.check:
        stale = stale_outputs(root, outputs)
        if stale:
            print("generated visitor guide differs from its source:")
            for path in stale:
                print(f"  {path}")
            print("regenerate and commit: uv run --locked python -m docs.how_it_works.render")
            return 1
        print("generated visitor guide is current")
        return 0
    write_outputs(root, outputs)
    print(f"generated {len(outputs)} visitor-guide files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
